### ISSUE TITLE
error in ios

### ISSUE THREAD

**Issue by TheoRevFdz** [jeroentrappers/flutter_bcrypt#1]
CocoaPods could not find compatible versions for pod "flutter_bcrypt":
  In Podfile:
    flutter_bcrypt (from `.symlinks/plugins/flutter_bcrypt/ios`)

Specs satisfying the `flutter_bcrypt (from `.symlinks/plugins/flutter_bcrypt/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by lambou** [comment]
Same issue

**Comment by mrinvicto** [comment]
Edit your pod file and add this at the top
`platform :ios, '9.3'`
