### ISSUE TITLE
Build failed on example

### ISSUE THREAD

**Issue by kadamowi** [jeroentrappers/flutter_bcrypt#4]
I try to use example file and it is generate build error:
Running Gradle task 'assembleDebug'...
e: D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_bcrypt-1.0.5\android\src\main\kotlin\be\appmire\flutter_bcrypt\FlutterBcryptPlugin.kt: (138, 31): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

**Comment by ShyamMurali** [comment]
does any one know any way around this .

**Comment by ShyamMurali** [comment]
line 138 is just log for error , if you just comment out that code , build works , this a temporary solution

**Comment by jeroentrappers** [comment]
Should be fixed. Thanks to https://github.com/ziakhan110 for the PR.
