### ISSUE TITLE
migrating the plugin to the V2 embedding

### ISSUE THREAD

**Issue by hansmboron** [jeroentrappers/flutter_bcrypt#8]
The plugin flutter_bcrypt uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing
it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration .

**Comment by flawnn** [comment]
Yep, we need this.

**Comment by FelipeSamuel** [comment]
Any updates?

**Comment by Freemanlabs** [comment]
+1

**Comment by ziakhan110** [comment]
please we need this

**Comment by robsonrung** [comment]
+1

**Comment by adarash** [comment]
+1

**Comment by DevinFlorentino** [comment]
Experiencing build failure. Will you be migrating this plugin soon?

**Comment by ziakhan110** [comment]
i made PR for this https://github.com/jeroentrappers/flutter_bcrypt/pull/9
i tested in 2 of my apps, its working fine.

**Comment by ziakhan110** [comment]
for build failing add mavenCentral() to top level build.gradle file

**Comment by jeroentrappers** [comment]
Thank you. This change has been merged.
